title: "Introduction to Git and GitHub"
remote_theme: ubc-library-rc/rc-theme
color_scheme: rc
github_repo_url: "https://github.com/TrentU-MaDGIC/MaDGIC.github.io"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
